<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <NoWarn>CS1591</NoWarn>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Debug|AnyCPU' ">
    <DocumentationFile>bin\Debug\EntityFrameworkCore.GraphManager.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <Authors>Adil Mammadov</Authors>
    <Description>Automatically define state of and handle graph of EntityFrameworkCore models with ease.</Description>
    <Copyright>Copyright 2023</Copyright>
    <PackageProjectUrl>https://github.com/MammadovAdil/EntityFrameworkCore.GraphManager</PackageProjectUrl>
    <RepositoryUrl>https://github.com/MammadovAdil/EntityFrameworkCore.GraphManager</RepositoryUrl>
    <PackageReleaseNotes>Upgrade to .Net 9</PackageReleaseNotes>
    <Title>EntityFrameworkCore.GraphManager by Adil Mammadov</Title>
    <PackageTags>entity-framework-core;graph;code-first;graph-manager</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageIcon>icon.png</PackageIcon>
    <PackageLicenseFile>License.md</PackageLicenseFile>
    <Version>9.0.0</Version>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\Resources\icon.png">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
    <None Include="..\Resources\License.md">
      <Pack>True</Pack>
      <PackagePath>\</PackagePath>
    </None>
  </ItemGroup>
  
  <ItemGroup>
    <PackageReference Include="Ma.ExtensionMethods" Version="9.0.0" />
    <PackageReference Include="Microsoft.CSharp" Version="4.7.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="9.0.0" />
    <PackageReference Include="System.ComponentModel.Annotations" Version="5.0.0" />
    <PackageReference Include="System.Data.DataSetExtensions" Version="4.5.0" />
  </ItemGroup>
</Project>